version: '3'
services:
  task-service:
    build: .
    ports:
      - "3001:3001"
    environment:
      - DB_ADMIN=$DB_ADMIN
      - DB_ADMIN_PWD=$DB_ADMIN_PWD
      - DB_NAME=$DB_NAME
      - DB_HOST=$DB_HOST
      - DB_PORT=$DB_PORT
      - PORT=3001
      - JWT_SECRET=$JWT_SECRET
      - CLIENT_KAFKA_ID=$CLIENT_KAFKA_ID
      - CLIENT_KAFKA_BROKERS=$CLIENT_KAFKA_BROKERS